// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuantityMeasurementAppRepoLayer.Data;

#nullable disable

namespace QuantityMeasurementRepoLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330094532_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuantityMeasurementAppModelLayer.Entities.QuantityMeasurementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ErrorMessage");

                    b.Property<bool>("HasError")
                        .HasColumnType("bit")
                        .HasColumnName("HasError");

                    b.Property<string>("Operand1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Operand1");

                    b.Property<string>("Operand2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Operand2");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Operation");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Result");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_QuantityMeasurements_CreatedAt");

                    b.HasIndex("HasError")
                        .HasDatabaseName("IX_QuantityMeasurements_HasError");

                    b.HasIndex("Operation")
                        .HasDatabaseName("IX_QuantityMeasurements_Operation");

                    b.ToTable("QuantityMeasurements", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
